export const ACTION_SET_NETWORK_CONN_STATUS = 'SET_NETWORK_CONN_STATUS';
export const ACTION_SET_TOKEN = 'SET_TOKEN';
export const ACTION_SET_USER_TYPE = 'SET_USER_TYPE';
export const ACTION_SET_CUSTOMER_SIGNUP_DATA = 'SET_CUSTOMER_SIGNUP_DATA';
export const ACTION_SET_USER_DATA = 'SET_USER_DATA';
export const ACTION_SET_SEARCH_CRITERIA = 'SET_SEARCH_CRITERIA';
export const ACTION_SET_BOOKING_DATA = 'SET_BOOKING_DATA';
export const ACTION_SET_FAVORITES = 'SET_FAVORITES';
export const ACTION_SET_SCHEDULE_CONFIRMATION_DATA =
  'SET_SCHEDULE_CONFIRMATION_DATA';
export const ACTION_SET_DR_BOOKING_HISTORY = 'SET_DR_BOOKING_HISTORY';
export const ACTION_SET_USER_SUPPORT = 'SET_USER_SUPPORT';
export const ACTION_SET_CURRENT_BOOKINGS = 'SET_CURRENT_BOOKINGS';
export const ACTION_SET_IS_PREMIUM_USER = 'SET_IS_PREMIUM_USER';
export const ACTION_SET_CONFIRMED_SCHEDULES = 'SET_CONFIRMED_SCHEDULES';
export const ACTION_SET_LOCATION = 'SET_LOCATION';
export const ACTION_SET_LOCATION_LIST = 'SET_LOCATION_LIST';
export const ACTION_SET_SPECIALIZATIONS = 'SET_SPECIALIZATIONS';
export const ACTION_SET_RECEIVED_INITIAL_DATA = 'SET_RECEIVED_INITIAL_DATA';
export const ACTION_SET_BOOKING_WITHOUT_FEEDBACK =
  'SET_BOOKING_WITHOUT_FEEDBACK';
export const ACTION_SET_USER_CURRENT_BOOKINGS = 'SET_USER_CURRENT_BOOKINGS';
export const ACTION_SET_USER_PAST_BOOKINGS = 'SET_USER_PAST_BOOKINGS';
